name: fastdvdnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cuda100=1.0
  - opencv=3.4.2
  - pip=20.0.2
  - pycodestyle=2.5.0
  - pytest=5.4.1
  - python=3.6.10
  - pytorch=1.0.0
  - scikit-image=0.16.2
  - torchvision=0.2.1
  - pip:
    - future==0.18.2
    - --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali==0.10.0
    - tensorboardx==2.0

